<?php


namespace frontend\modules\accounts\filters;

use Yii;
use yii\base\ActionFilter;

/**
 * 申明一个记录动作执行时间日志的过滤器
 * Class ActionTimeFilter
 */
class ActionTimeFilter extends ActionFilter
{
	private $_startTime;

	public function beforeAction($action): bool {
		$this->_startTime = microtime(TRUE);
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}

	public function afterAction($action , $result) {
		$time = microtime(TRUE) - $this->_startTime;
		Yii::debug("Action '{$action->uniqueId}' spent $time second.");
		print_r("控制器里的过滤器：" . $action->getUniqueId() . "<br/>");
		return parent::afterAction($action , $result); // TODO: Change the autogenerated stub
	}
}
