<?php


namespace frontend\filters;

use Yii;
use yii\base\ActionFilter;

/**
 * 申明一个记录动作执行时间日志的过滤器
 * Class ActionTimeFilter
 */
class MainAppFilter extends ActionFilter
{
	private $_startTime;

	public function beforeAction($action) {
		$this->_startTime = microtime(TRUE);
		return parent::beforeAction($action); // TODO: Change the autogenerated stub
	}

	public function afterAction($action , $result) {
		$time = microtime(TRUE) - $this->_startTime;
		print_r("应用层的过滤器：" . $action->getUniqueId() . "<br/>");
		return parent::afterAction($action , $result); // TODO: Change the autogenerated stub
	}
}
